apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: data
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: data
    flexVolume:
      driver: "sysoperator.pl/lvm"
      fsType: "ext4"
      options:
        volumeID: "data"
        size: "10g"
        volumegroup: "storage"
        mountoptions: "relatime,nobarrier"
